# theme: minimal-mistakes-jekyll
# remote_theme: pmarsceill/just-the-docs
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: NSEDownload
description: Python Library to get historical data and generate trailing returns of stocks and indices on the NSE
url: https://nsedownload.github.io/
baseurl: NSEDownload/
repository: NSEDownload/NSEDownload
