remote_theme: pmarsceill/just-the-docs
title: NSEDownload
description: Python Library to get historical data and generate trailing returns of stocks and indices on the NSE
search_enabled: false
aux_links:
  "NSEDownload on GitHub":
    - "https://github.com/NSEDownload/NSEDownload"
aux_links_new_tab: true
nav_exclude: true
